### ISSUE TITLE
Sales Activity - Timeline

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Mobile#2]
- [x] OpenERP API untuk memanggil sql  view activty_plan
- [x] Django Module untuk Rest konek ke Json OpenERP Api
- [x] View ionic untuk **Sales Activity Timeline**

**Comment by lajayuhniyarsyah** [comment]
@Mohammadrezafah : PLease konsentrasi ke modul diatas

**Comment by Mohammadrezafah** [comment]
berarti saya tinggal View ionic untuk Sales Activity Timeline mas jay ..

**Comment by lajayuhniyarsyah** [comment]
Iya... method nya seperti yg dibicarain semalem

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : bantu ya

**Comment by Mohammadrezafah** [comment]
@lajayuhniyarsyah : 
ada masalah untuk pengecekan data terbaru di table views karena tidak ada ID

**Comment by lajayuhniyarsyah** [comment]
Bisa di cek dari beberapa field yg sy udah bilang waktu lalu

Dari field tanggal,user id,dow, trus beberapa lagi

**Comment by Mohammadrezafah** [comment]
@lajayuhniyarsyah : mas jay silahkan di cek http://10.36.15.53:8100/#/sales-activity-timeline , 
takut ada revisi, atau tambahan .

**Comment by Mohammadrezafah** [comment]
@lajayuhniyarsyah : mas jay tolong di cek http://10.36.15.53:8100/#/sales-timeline , takut ada yang kurang ?
