### ISSUE TITLE
Perbaikan Template Sales Plan dan Activity

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Mobile#20]
Di template baru yang dibuat oleh @ekachandrasetiawan pada pull request #13 ,, ada background yang berwarna ungu.

Mohon dilanjutkan untuk redesign template untuk di semua form dan module Plan Activity.

**Comment by lajayuhniyarsyah** [comment]
Di #21 
Itu form field Objective nya kenapa pakai input text ??

Objective itu kan dipakai untuk mengisi keterangan,, yang panjangnya bisa unlimit,, bisa menghandle itu ga kalau pake input text ???

**Comment by ekachandrasetiawan** [comment]
untuk Menu Slide 

Ada sedikit masalah, 
Tidak bisa tampil di semua content jika menu tidak di akses dari menu slide,

Jadi jika menu di akses dari button maka di page yang di akses menu slide tidak akan keluar, sedangkan jika di akses dari menu slide di page yang sama menu slide akan tampil
